42-Jolly-pingpong/front-end

src/components/sidebar/friend/friend-requested.tsx, src/pages/create-chat/components/private-room-field.tsx
input에 checked속성을 넣고 onClick 이벤트 함수를 함께 사용해서 나는 워닝이었습니다. onChange로 바꿔 해결했습니다.
- #12
=> [fix] input태그 워닝 해결 #12

src/app.tsx
=> [chore] 채팅방 생성 url 변경 #15

src/app.tsx, src/components/avatar/avatar.tsx, src/components/sidebar/friend/friend-element.tsx, src/components/sidebar/inchat/chat-bubble.tsx, src/components/user-info/info-button.tsx, src/components/user-info/user-info.tsx, src/components/user-info/user-short-profile.tsx
user info 컴포넌트 뷰 구현
아바타를 누르면  user info 컴포넌트로 리다이렉션 되도록 했습니다.
각종 필요한 버튼이 프로필 아래에 배치되도록 했습니다.
온클릭 이벤트들은 적절한 api가 만들어지면 추후 수정할 예정입니다.
- #6
=> [feat] user info 컴포넌트 뷰 구현 #6

src/components/avatar/avatar.tsx, src/components/sidebar/friend/friend-element.tsx, src/components/sidebar/inchat/chat-bubble.tsx, src/components/user-info/user-info.tsx
챗룸 내부 ui를 변경했습니다.
챗룸 내부 ui를 변경했습니다
내가 보낸 메시지에는 아바타와 닉네임이 나오지 않도록 했습니다.
여전히 스크롤은 안됩니다..
- #28
=> [fix] a chat room 내부 ui 변경 #28

src/app.tsx, src/components/avatar/avatar.tsx, src/components/user-info/user-info.tsx
user-info url 변경, onclick이벤트 추가
- user정보를 쿼리파람으로 받아왔습니다.
- 채팅하기 onClick이벤트를 추가했습니다.
- #32
=> [feat] user-info url 변경, onclick이벤트 추가 #32

package-lock.json, package.json, tailwind.config.js, vite.config.ts
Flowbite 추가했슴다
Flowbite를 추가했는데 Daisy UI를 지우니깐 깨지는 부분이 있어서 아직 지우지 않았습니다.
피그마로 디자인이 나오고 전환이 다 완료된 이후 해당 브랜치에서 제거하고 다시 PR을 올리도록 하겠습니다 😃
- #39
=> [fix] move daisy UI to flowbite #39

.github/ISSUE_TEMPLATE/component.md
깃 이슈 템플릿 텍스트 수정
[component]가 길어서 [feat] 처럼 [comp]로 줄입니다.
change component -> comp in title
-
=> [chore] 이슈 템플릿 component.md  수정

tailwind.config.js
- theme를 적용하고 primary컬러를 추가했습니다.
- color를 사용자화하여 primary색상을 추가했습니다.
- #108
=> [feat] theme적용, primary color 적용 #108

src/pages/profile/components/header/field/profile-badge.tsx, src/pages/profile/components/tab/field/friend/profile-friend-list-normal.tsx, src/pages/profile/components/tab/field/game-history/profile-game-history-list.tsx
없는 유저의 프로필을 볼 때, 리스트 불러오는 도중 발생했던 에러 핸들링 완료했습니다.
-
=> [fix] 없는 유저의 프로필

src/app.tsx, src/pages/error/page-404.tsx
없는 url에 접근했을 때, 보여줄 404 페이지를 만들었습니다.
-
=> [comp] error page

src/pages/chat/components/modal/search-channel-item.tsx, src/pages/chat/components/sidebar/chat-information-tap.tsx, src/pages/chat/components/sidebar/chat-setting-tap.tsx
- 채널 나가기 버튼을 눌렀을 경우 모달을 띄워 다시 한번 확인합니다.
- 채널 나가기 버튼을 눌렀을 경우 모달을 띄워 다시 한번 확인합니다.
- 채널 타입이 변경될 때 모달을 띄워 다시 한번 확인합니다.
- 프로텍티드 채널의 비밀번호를 변경할 때 변경할 비밀번호가 비어있으면 인풋 색을 바꿔 알려줍니다.
- 수정 중 발견한 에러를 해결했습니다.
- #113
=> [feat] leave a channel #113 

src/pages/chat/components/big-user-img.tsx, src/pages/chat/components/field/dm-header.tsx, src/pages/chat/components/header/chat-header-search.tsx, src/pages/chat/components/header/chat-header-title.tsx, src/pages/chat/components/modal/set-chat-room-name.tsx, src/pages/chat/components/sidebar/chat-member-inquire-tap.tsx, src/pages/chat/components/sidebar/chat-sidebar-profile.tsx, src/pages/chat/components/sidebar/member-item.tsx, src/pages/chat/components/user-img.tsx
- 디엠 헤더 사용자 누르면 프로필이 나오도록 했습니다.
- #98
=> [feat] 디엠 채팅 헤더 누르면 프로필 나옴 #98

package-lock.json, src/app.tsx
어제 PR 볼때 백엔드에서 오타난거 찾은거 고치고 여기도 수정했어요
opt -> otp로 바꿨습니다
- #153
=> [fix] 오타 수정 #153

src/app.tsx, src/components/layout/layout.tsx, src/pages/chat/chat.tsx, src/pages/chat/components/big-user-img.tsx
- 챗 레이아웃에 추가
- css 워닝뜨는 부분 수정
- #162
=> [fix] handle any bug on chat #162

Dockerfile, src/api/sendAPI.ts, src/components/root/welcome/components/login-button.tsx, src/hooks/use-fetch.tsx, src/pages/chat/chat-socket.tsx, src/pages/game/game.tsx, src/socket/socket.tsx
[긴급] 환경변수 추가했어요.
환경변수 참고하는 프론트엔드 파일을 수정
-
=> [feat] show score history when button clicked #71

src/components/layout/friend-sidebar/field/friend-search-list.tsx, src/components/layout/friend-sidebar/field/friend-sidebar-list.tsx, src/components/layout/friend-sidebar/field/friend-sidebar-search.tsx, src/components/layout/friend-sidebar/item/friend-dropdown.tsx, src/components/layout/friend-sidebar/item/friend-info.tsx, src/ts/enums/profile/profile-status.enum.ts
enum 되돌리기
오류난다고 하는 부분때문에 수정했어요. 테스트는 안해봤습니다 ㅜ
친구 목록 CSS도 수정
-
=> [fix] enum 수정 

src/pages/chat/chat-alert-modal.tsx, src/pages/chat/components/chat-input.tsx, src/pages/chat/components/modal/search-channel-item.tsx, src/pages/chat/components/sidebar/inquire-tap/member-dot-button.tsx, src/pages/chat/components/sidebar/profile/profile-dot-button.tsx
- css수정했습니딝
- 친구 요청 상태에 따라 버튼 문구와 처리가 달라지게 했습니다
-
=> [fix] handle any bug on chat

src/components/banner/banner.tsx, src/components/banner/game-request-banner.tsx, src/components/banner/inviteCancel-banner.tsx, src/components/banner/theme/progress-theme.tsx, src/components/modal/game-search-modal.tsx, src/components/modal/game-wait-modal.tsx, src/components/modal/item/game-mode-select.tsx, src/constants/values.ts, src/pages/game/components/roundInfo.tsx, src/pages/main/components/join-button.tsx, src/ts/enums/game/game-banner.enum.ts, src/ts/enums/game/game-mode.enum.ts
게임 초대를 거절했을경우 및 거절 당했을경우 상대 클라이언트에게 알리는 컴포넌트 생성
게임 초대 후 10초 안에 수락하지 않을시 상대 클라이언트에게 알리는 컴포넌트 생성
-
=> 173 feat invite cancel

src/pages/game/components/playerProfile.tsx
=> [fix] 게임시 유저 프로필에 nickname이 아닌 intrid가 뜨는 문제와 프로필 사진이 나오지 않는 문제 해결

index.html, src/components/layout/friend-sidebar/field/friend-search-list.tsx, src/components/layout/friend-sidebar/field/friend-sidebar-list.tsx, src/pages/chat/chat.tsx, src/pages/chat/components/big-user-img.tsx, src/pages/chat/components/chat-content.tsx, src/pages/chat/components/chat-input.tsx, src/pages/chat/components/field/chat-field.tsx, src/pages/chat/components/header/chat-header-search.tsx, src/pages/chat/components/header/chat-header-title.tsx, src/pages/chat/components/sidebar/chat-sidebar.tsx, src/pages/profile/components/tab/field/game-history/item/profile-game-history-item.tsx, src/pages/profile/components/tab/field/game-history/profile-game-history-list.tsx
CSS 수정
flex로 감싸고 grid쪽은 flex 속성 쓰인 곳 삭제
-
=> [fix] 채널 생성하고 이상하게 보이는 거 수정 #189

src/pages/profile/components/header/item/social/profile-social-dropdown.tsx
=> feat: 프로필에 게임 시작 버튼 활성화

src/components/banner/game-request-banner.tsx, src/components/modal/item/game-mode-select.tsx
=> [refactor] 게임 배너 및 게임 초대 모달 css 수정

src/hooks/use-change-chat.tsx
- 챗룸 들어갈 때 정보 새로 가져오도록 했습니다.
-
=> [fix] 챗룸 들어갈 때 정보 새로 가져오도록 함

src/components/layout/friend-sidebar/item/friend-dropdown.tsx, src/pages/chat/components/sidebar/profile/profile-field.tsx, src/pages/profile/components/header/item/social/profile-social-dropdown.tsx
=> feat: 상대 유저가 접속중이 아닌경우 게임 초대 버튼을 누를수 없게 변경

src/components/banner/banner.tsx
=> fix: 초대 요청을 취소하면 상대방에게 취소 메세지의 nickname이 undefine으로 표시되는 문제 해결

src/pages/chat/components/sidebar/inquire-tap/member-dot-button.tsx, src/pages/chat/components/sidebar/profile/profile-dot-button.tsx
=> [fix] 차단 유저 목록 업데이트함

src/hooks/use-hash.tsx, src/pages/chat/components/modal/search-channel-item.tsx, src/pages/chat/components/modal/set-chat-room-type.tsx, src/pages/chat/components/sidebar/setting-tap/channel-room-type-field.tsx
- 암호화 방식을 변경했습니다.
- 기존 웹 api로 해쉬를 하다가 secure origin이 아닌 경우 문제가 생겼고 호환되는 라이브러리를 찾지못해 변경했습니다.
-
=> [fix] 해쉬 방식 변경

src/pages/game/game.tsx
=> fix: 게임 페이지에서 새로고침시 잘못된 요청을 보내는 경우 해결

src/pages/chat/components/sidebar/history-doughnut-chart.tsx
=> [fix] 도넛 차트 라벨 지움

src/pages/profile/components/modal/item/profile-edit-avatar.tsx, src/pages/profile/components/modal/profile-edit-modal.tsx
이미지 5MB일때 알럿 표시
이미지 5MB일때 알럿뜨고 수정 방지
-
=> [fix] 이미지 업로드 제한 #203
